### PR TITLE
PR for moving forward with the backend on arheo. - User management feature with JWT. -  Will implement tests.

### PR DESCRIPTION
**Pull request by dunmer0**
Implemented user management feature.
Features implemented:Login, Register, ResetPassword, etc. Admin can modifiy users, users can modify only themselves. The endpoints are protected based on role.

### CODE REVIEW

**Review by CalinescuFlorin — APPROVED** [review]

**Review by BlastOfMihh — APPROVED** [review]
this is very good

**Review by AlisaUrsu — APPROVED** [review]

**Review by deea-20 — APPROVED** [review]
good work!

**Review by DragosButnar — APPROVED** [review]

**Review by cristibercea — APPROVED** [review]
respect, good job!

**Comment by MihaiS-git** [comment]
good to go!

**Review by MihaiS-git — APPROVED** [review]

**Review by tibumanu — APPROVED** [review]

**Pull request merged**
